import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import { fixtureZip } from './shapefile-fixture.js';
test('downloaded HTML imports, analyzes, renders, and exports without a server or network', async ({ page, context }) => {
  const errors = [], remoteRequests = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', request => { if (/^https?:/.test(request.url())) remoteRequests.push(request.url()); });
  await context.setOffline(true);
  // The managed test browser blocks file:// URLs. Load the exact downloaded
  // document into an isolated blank page without serving it over HTTP.
  await page.setContent(readFileSync(resolve('standalone/index.html'), 'utf8'));
  await page.locator('#demo').click();
  await expect(page.locator('#total')).toHaveText('8');
  await expect(page.locator('#viewer canvas')).toBeVisible();
  await expect(page.locator('.webgl-error')).toHaveCount(0);
  const settle = () => page.evaluate(async () => { for (let i = 0; i < 8; i++) await new Promise(requestAnimationFrame); });
  await settle();
  const withMarkers = await page.locator('#viewer canvas').screenshot();
  await page.locator('#show-markers').uncheck(); await settle();
  const withoutMarkers = await page.locator('#viewer canvas').screenshot();
  expect(withoutMarkers.equals(withMarkers)).toBe(false);
  await page.locator('#show-markers').check(); await settle();
  expect((await page.locator('#viewer canvas').screenshot()).equals(withoutMarkers)).toBe(false);
  await page.locator('#show-markers').uncheck();
  await page.locator('[data-filter="clash"]').click();
  await page.locator('.inspect').click();
  await expect(page.locator('#crossing-detail')).toContainText('vertical overlap');
  await page.locator('#top').click();
  await page.locator('#fit').click();
  await page.locator('#file-input').setInputFiles({ name: 'network.zip', mimeType: 'application/zip', buffer: fixtureZip(false, false, true) });
  await expect(page.locator('#map-up')).toHaveValue('US_Invert');
  await expect(page.locator('#map-shape')).toHaveValue('SHAPE');
  await expect(page.locator('#geometry-info')).toContainText('1 circular · 1 box pipes');
  await page.locator('#analyze').click();
  await expect(page.locator('#total')).toHaveText('1');
  await expect(page.locator('#show-markers')).not.toBeChecked();
  await page.locator('#show-markers').check();
  await expect(page.locator('.clearance')).toHaveText('-0.500');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  const stream = await download.createReadStream();
  let text = ''; for await (const chunk of stream) text += chunk.toString();
  expect(text).toContain('P-A'); expect(text).toContain('-0.5');
  expect(errors).toEqual([]); expect(remoteRequests).toEqual([]);
});
